<nav>
  <ul id="menu">
    <li>
      <a href="#">Home</a>
    </li>
    <li>
      <a href="#">About This Course</a>
    </li>
    <li>
      <a href="#" class="drop">Lectures</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="lectures/lecture1.html">Lecture 1</a>
            </li>
            <li>
              <a href="lectures/lecture2.html">Lecture 2</a>
            </li>
            <li>
              <a href="lectures/lecture3.html">Lecture 3</a>
            </li>
            <li>
              <a href="lectures/lecture4.html">Lecture 4</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="lectures/lecture5.html">Lecture 5</a>
            </li>
            <li>
              <a href="lectures/lecture6.html">Lecture 6</a>
            </li>
            <li>
              <a href="lectures/lecture7.html">Lecture 7</a>
            </li>
            <li>
              <a href="lectures/lecture8.html">Lecture 8</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="lectures/lecture9.html">Lecture 9</a>
            </li>
            <li>
              <a href="lectures/lecture10.html">Lecture 10</a>
            </li>
            <li>
              <a href="lectures/lecture11.html">Lecture 11</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li>
      <a href="#" class="drop">Exercises/Solutions</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="exercises/lecture1_exercises.html">Exercises/Solutions 1</a>
            </li>
            <li>
              <a href="exercises/lecture2_exercises.html">Exercises/Solutions 2</a>
            </li>
            <li>
              <a href="exercises/lecture3_exercises.html">Exercises/Solutions 3</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="exercises/lecture4_exercises.html">Exercises/Solutions 4</a>
            </li>
            <li>
              <a href="exercises/lecture5_exercises.html">Exercises/Solutions 5</a>
            </li>
            <li>
              <a href="exercises/lecture6_exercises.html">Exercises/Solutions 6</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="exercises/lecture7_exercises.html">Exercises/Solutions 7</a>
            </li>
            <li>
              <a href="exercises/lecture8_exercises.html">Exercises/Solutions 8</a>
            </li>
            <li>
              <a href="exercises/lecture9_exercises.html">Exercises/Solutions 9</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li>
      <a href="#" class="drop">Homework</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="homework/homework1.html">Homework 1</a>
            </li>
            <li>
              <a href="homework/homework2.html">Homework 2</a>
            </li>
            <li>
              <a href="homework/homework3.html">Homework 3</a>
            </li>
            <li>
              <a href="homework/homework4.html">Homework 4</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="homework/homework5.html">Homework 5</a>
            </li>
            <li>
              <a href="homework/homework6.html">Homework 6</a>
            </li>
            <li>
              <a href="homework/homework7.html">Homework 7</a>
            </li>
            <li>
              <a href="homework/homework8.html">Homework 8</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="homework/homework9.html">Homework 9</a>
            </li>
            <li>
              <a href="homework/finalproject.html">Final Project</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li>
      <a href="#" class="drop">Quizzes</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="quizzes/quiz1.html">Quiz 1</a>
            </li>
            <li>
              <a href="quizzes/quiz2.html">Quiz 2</a>
            </li>
            <li>
              <a href="quizzes/quiz3.html">Quiz 3</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="quizzes/quiz4.html">Quiz 4</a>
            </li>
            <li>
              <a href="quizzes/quiz5.html">Quiz 5</a>
            </li>
            <li>
              <a href="quizzes/quiz6.html">Quiz 6</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="quizzes/quiz7.html">Quiz 7</a>
            </li>
            <li>
              <a href="quizzes/quiz8.html">Quiz 8</a>
            </li>
            <li>
              <a href="quizzes/finalexam.html">Final Exam</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li>
      <a href="#" class="drop">Resources</a>
      <div class="dropdown_3columns">
        <div class="col_1">
          <ul>
            <li>
              <a href="resources/lecture1_resources.html">Resources 1</a>
            </li>
            <li>
              <a href="exercises/lecture2_resources.html">Resources 2</a>
            </li>
            <li>
              <a href="exercises/lecture3_resources.html">Resources 3</a>
            </li>
            <li>
              <a href="exercises/lecture4_resources.html">Resources 4</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="exercises/lecture5_resources.html">Resources 5</a>
            </li>
            <li>
              <a href="exercises/lecture6_resources.html">Resources 6</a>
            </li>
            <li>
              <a href="exercises/lecture7_resources.html">Resources 7</a>
            </li>
            <li>
              <a href="exercises/lecture8_resources.html">Resources 8</a>
            </li>
          </ul>
        </div>
        <div class="col_1">
          <ul>
            <li>
              <a href="exercises/lecture9_resources.html">Resources 9</a>
            </li>
            <li>
              <a href="exercises/lecture10_resources.html">Resources 10</a>
            </li>
            <li>
              <a href="exercises/lecture11_resources.html">Resources 11</a>
            </li>
          </ul>
        </div>
      </div>
    </li>
    <li class="menu_right">
      <a href="https://my.bcit.ca/cp/home/displaylogin">my.bcit.ca</a>
    </li>
  </ul>
</nav>