<div class="rightnav">

  <h1>COMP 1950 SiteMap</h1>
  <h2>Preliminary Site Map &mdash; Version 1.0</h2>

  <ul id="utilityNav">
    <li>
      <a href="http://my.bcit.ca">my.bcit.ca</a>
    </li>
    <li>
      <a href="/sitemap">Site Map</a>
    </li>
  </ul>

  <ul id="primaryNav" class="col8">
    <li id="home">
      <a href="http://sitetitle.com">
        Home<br />
        - Room Information <br />
        - Timetable <br />
        - BCIT Policies <br />
        - Instructor Contact <br />
      </a>
    </li>
    <li>
      <a href="/about">
        About This Course
        - Curriculum <br />
        - Grading <br />
      </a>
    </li>
    <li>
      <a href="/lectures">Lectures</a>
      <ul>
        <li>
          <a href="/lectures/lecture1">01| Tools & Standards</a>
          <ul>
            <li>
              <a href="/exercises/lecture1_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework1">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture1_resources">Resources</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture2">02| Html5</a>
          <ul>
            <li>
              <a href="/exercises/lecture2_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework2">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture2_resources">Resources</a>
            </li>
            <li>
              <a href="/quizzes/quiz1">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture3">03| CSS Techniques</a>
          <ul>
            <li>
              <a href="/exercises/lecture3_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework3">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture3_resources">Resources</a>
            </li>
            <li>
              <a href="/quizzes/quiz2">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture4">04| CSS Layouts</a>
          <ul>
            <li>
              <a href="/exercises/lecture4_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework4">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture4_resources">Resources</a>
            </li>
            <li>
              <a href="/quizzes/quiz3">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture5">05| Responsive CSS</a>
          <ul>
            <li>
              <a href="/exercises/lecture5_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework5">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture5_resources">Resources</a>
            </li>
            <li>
              <a href="/quizzes/quiz4">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture6">06| CSS3</a>
          <ul>
            <li>
              <a href="/exercises/lecture6_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework6">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture6_resources">Resources</a>
            </li>
            <li>
              <a href="/quizzes/quiz5">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture7">07| Javascript Frameworks</a>
          <ul>
            <li>
              <a href="/exercises/lecture7_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework7">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture7_resources">Resources</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture8">08| Dynamic Content</a>
          <ul>
            <li>
              <a href="/exercises/lecture8_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework8">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture8_resources">Resources</a>
            </li>
            <li>
              <a href="/quizzes/quiz6">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture9">09| Templating, SEO</a>
          <ul>
            <li>
              <a href="/exercises/lecture9_exercises">Exercises/Solutions</a>
            </li>
            <li>
              <a href="/homework/homework9">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture9_resources">Resources</a>
            </li>
            <li>
              <a href="/quizzes/quiz7">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture10">10| Methodology</a>
          <ul>
            <li>
              <a href="/homework/homework10">Homework</a>
            </li>
            <li>
              <a href="/resources/lecture10_resources">Resources</a>
            </li>
            <li>
              <a href="/lectures/lecture8/quiz">Quiz</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="/lectures/lecture11">11| Project Work</a>
          <ul>
            <li>
              <a href="/homework/finalproject">Final Project</a>
            </li>
            <li>
              <a href="/resources/lecture11_resources">Resources</a>
            </li>
          </ul>
        </li>
      </ul>
    </li>
</div>