     <nav>
     <!--navigation for the widescreen starts from here -->
     <ul>
   		<li class='active has-sub'><a href='#'><span>About COMP1950</span></a>
   			<ul>
   			 <li class='has-sub'><a href='#'><span>Curriculum</span></a><li>
   			 <li class='has-sub'><a href='#'><span>Grading Policy</span></a><li>


   			</ul>
   		
   		</li>
   		
   		
   		<li class='active has-sub'><a href='#'><span>Lectures</span></a>

      		  <ul>
         		<li class='has-sub'><a href='#'><span>01-Tools & Standards</span></a>
            		<ul>
              			 <li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework01</span></a></li>
            		</ul>
         		</li>
         	    <li class='has-sub'><a href='#'><span>02-HTML5</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='has-sub'><a href='#'><span>Homework02</span></a></li>
            		</ul>
         		</li>
         		<li class='has-sub'><a href='#'><span>03-CSS Techniques</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework03</span></a></li>
            		</ul>
         		</li>
         		<li class='has-sub'><a href='#'><span>04-CSS Layouts</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework04</span></a></li>
            		</ul>
         		</li>
         			<li class='has-sub'><a href='#'><span>05-Responsive CSS</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework05</span></a></li>
            		</ul>
         		</li>
         		<li class='has-sub'><a href='#'><span>06-CSS3</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
            		</ul>
         		</li>
         		<li class='has-sub'><a href='#'><span>07-JavaScript Frameworks</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework06</span></a></li>
            		</ul>
         		</li>
         		<li class='has-sub'><a href='#'><span>08-Dynamic Content</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework07</span></a></li>
            		</ul>
         		</li>
         		<li class='has-sub'><a href='#'><span>09-Templating,SEO</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework08</span></a></li>

            		</ul>
         		</li>
         		<li class='has-sub'><a href='#'><span>10-Methodology</span></a>
            		<ul>
               			<li><a href='#'><span>Notes</span></a></li>
               			<li class='last'><a href='#'><span>Homework09</span></a></li>

            		</ul>
            	</li>
            	<li class='has-sub'><a href='#'><span>11-Project Work</span></a>
					<ul>
               			<li class='last'><a href='#'><span>Notes</span></a></li>
               		</ul>	
                </li>
     	  </ul>
   				</li>
   			  <li class='active has-sub'><a href='#'><span>Exercises</span></a>
      		  <ul>
         		<li class='has-sub'><a href='#'><span>Lecture 1</span></a>
         		</li>
         		<li class='has-sub'><a href='#'><span>Lecture 2</span></a>
            	<li class='has-sub'><a href='#'><span>Lecture 3</span></a>
            	<li class='has-sub'><a href='#'><span>Lecture 4</span></a>
            	<li class='has-sub'><a href='#'><span>Lecture 5</span></a>
            	<li class='has-sub'><a href='#'><span>Lecture 6</span></a>
            	<li class='has-sub'><a href='#'><span>Lecture 7</span></a>
            	<li class='has-sub'><a href='#'><span>Lecture 8</span></a>
            	<li class='has-sub'><a href='#'><span>Lecture 9</span></a>	
            	<li class='last'><a href='#'><span>Lecture 10</span></a>	
         		</li>
     	  </ul>
   				</li>
   				<li class='active has-sub'><a href='#'><span>Quizzes</span></a>
   				  <ul>
         		<li class='has-sub'><a href='#'><span>Quiz 1</span></a>
         		</li>
         		<li class='has-sub'><a href='#'><span>Quiz 2</span></a>
            	<li class='has-sub'><a href='#'><span>Quiz 3</span></a>
            	<li class='has-sub'><a href='#'><span>Quiz 4</span></a>
            	<li class='has-sub'><a href='#'><span>Quiz 5</span></a>
            	<li class='has-sub'><a href='#'><span>Quiz 6</span></a>
            	<li class='has-sub'><a href='#'><span>Quiz 7</span></a>
            	<li class='last'><a href='#'><span>Quiz 8</span></a>	
         		</li>
     	  </ul>
   				</li>
   				<li><a href='#'><span>Resources</span></a></li>
   				<li class='active has-sub'><a href='#'><span>Contact The Instructor</span></a>
   					<ul>
   					<li class='last'><a href='#'><span>Jeffry Parker</span></a></li>	
   					</ul>
   					</li>
   				<li class='active has-sub'><a href="https://my.bcit.ca/cp/home/displaylogin" target="_blank"><span>My.bcit</span></a>
   				</li>

            
		</ul>
     	<!--navigation  for the wide screen ends from here -->
        </nav>
  